export enum NotificationTuri {
  YANGI_TOPSHIRIQ = 'YANGI_TOPSHIRIQ',
  MUDDAT_3_KUN = 'MUDDAT_3_KUN',
  MUDDAT_1_KUN = 'MUDDAT_1_KUN',
  MUDDAT_2_SOAT = 'MUDDAT_2_SOAT',
  MUDDAT_OTDI = 'MUDDAT_OTDI',
  QAYTARILDI = 'QAYTARILDI',
  TASDIQLANDI = 'TASDIQLANDI',
  ESKALATSIYA = 'ESKALATSIYA',
}
